# Generated by Django 5.1.7 on 2025-03-26 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alarmes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('Non lue', 'Non lue'), ('Lue', 'Lue'), ('Ignorée', 'Ignorée')], default='Non lue', max_length=50)),
                ('canal', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Push', 'Push Notification')], default='Email', max_length=50)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('alarme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alarmes.alarme')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
