FROM node:20-slim

WORKDIR /app

COPY package*.json ./
COPY .env.local .env 

RUN rm -rf node_modules package-lock.json \
  && npm install --legacy-peer-deps

COPY . .

EXPOSE 5173

CMD ["npx", "vite"]
