FROM node:20-slim

WORKDIR /app

COPY ./frontend/package*.json ./

RUN rm -rf node_modules package-lock.json \
  && npm install --legacy-peer-deps

COPY ./frontend .

EXPOSE 5173

CMD ["npx", "vite"]
