# Generated by Django 5.1.7 on 2025-04-16 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet de la réclamation')),
                ('message', models.TextField(verbose_name='Message détaillé')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name='Date d’envoi')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.installation', verbose_name='Installation concernée')),
            ],
        ),
    ]
