# Generated by Django 5.1.6 on 2025-05-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet de la réclamation')),
                ('message', models.TextField(verbose_name='Message détaillé')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name='Date d’envoi')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu')], default='en_attente', max_length=20, verbose_name='Statut')),
            ],
        ),
        migrations.CreateModel(
            name='ReclamationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reclamations/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
