# Generated by Django 5.1.6 on 2025-05-21 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installations', '0002_initial'),
        ('reclamation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.installation', verbose_name='Installation concernée'),
        ),
        migrations.AddField(
            model_name='reclamationimage',
            name='reclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reclamation.reclamation'),
        ),
    ]
