# Generated by Django 5.1.7 on 2025-05-14 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reclamations/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reclamation.reclamation')),
            ],
        ),
    ]
