# Generated by Django 5.1.7 on 2025-04-14 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='technicien_assigne',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Techniciens'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens', to=settings.AUTH_USER_MODEL),
        ),
    ]
