# Generated by Django 5.1.6 on 2025-05-21 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entretien', '0001_initial'),
        ('installations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='entretien_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doublons', to='entretien.entretien'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='installations.installation'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='technicien',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'technicien'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Technicien assigné'),
        ),
        migrations.AddField(
            model_name='evenementgoogleparutilisateur',
            name='entretien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_google', to='entretien.entretien'),
        ),
        migrations.AddField(
            model_name='evenementgoogleparutilisateur',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='googletoken',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rappelentretien',
            name='entretien',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rappel', to='entretien.entretien'),
        ),
        migrations.AddField(
            model_name='rappelentretien',
            name='technicien',
            field=models.ForeignKey(limit_choices_to={'role': 'technicien'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='evenementgoogleparutilisateur',
            unique_together={('utilisateur', 'entretien')},
        ),
    ]
