# Generated by Django 5.1.7 on 2025-05-18 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0002_googletoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementGoogleParUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('entretien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_google', to='entretien.entretien')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'entretien')},
            },
        ),
    ]
