# Generated by Django 5.1.7 on 2025-04-14 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0003_alter_entretien_technicien_assigne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entretien',
            name='technicien_assigne',
        ),
        migrations.AddField(
            model_name='entretien',
            name='technicien',
            field=models.ForeignKey(limit_choices_to={'role': 'technicien'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entretiens_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Technicien assigné'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
