# Generated by Django 5.1.7 on 2025-04-15 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0004_remove_entretien_technicien_assigne_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entretien',
            options={'ordering': ['date_debut'], 'permissions': [('planifier_entretien', 'Peut planifier un entretien'), ('annuler_entretien', 'Peut annuler un entretien')], 'verbose_name': 'Entretien', 'verbose_name_plural': 'Entretiens'},
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='date_entretien',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='prochain_entretien',
        ),
        migrations.AddField(
            model_name='entretien',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de début'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='duree_estimee',
            field=models.PositiveIntegerField(default=60, help_text='Durée estimée en minutes'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes supplémentaires'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='priorite',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('elevee', 'Élevée'), ('normale', 'Normale'), ('basse', 'Basse')], default='normale', max_length=20),
        ),
        migrations.AddField(
            model_name='entretien',
            name='rapport',
            field=models.FileField(blank=True, null=True, upload_to='rapports_entretien/', verbose_name="Rapport d'intervention"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='statut',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='technicien',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'technicien'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Technicien assigné'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='type_entretien',
            field=models.CharField(choices=[('preventif', 'Préventif'), ('correctif', 'Correctif'), ('annuel', 'Contrôle annuel'), ('trimestriel', 'Contrôle trimestriel')], default='preventif', max_length=20),
        ),
    ]
