# Generated by Django 5.1.6 on 2025-04-25 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0006_entretien_titre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RappelEntretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rappel_datetime', models.DateTimeField(help_text='Date et heure exacte du rappel')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('entretien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rappel', to='entretien.entretien')),
                ('technicien', models.ForeignKey(limit_choices_to={'role': 'technicien'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
