# Generated by Django 5.1.7 on 2025-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0007_rappelentretien'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='periode_recurrence',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 mois'), (3, '3 mois'), (6, '6 mois'), (12, '12 mois')], help_text='Créer automatiquement un entretien récurrent après cette période (en mois)', null=True),
        ),
    ]
