# Generated by Django 5.1.7 on 2025-05-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0008_entretien_periode_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='event_id_google',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="ID de l'événement Google Calendar"),
        ),
    ]
