# Generated by Django 5.1.7 on 2025-05-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0009_entretien_event_id_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='lien_evenement_google',
            field=models.URLField(blank=True, null=True, verbose_name='Lien vers l’événement Google Calendar'),
        ),
    ]
