# Generated by Django 5.1.7 on 2025-05-12 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0010_entretien_lien_evenement_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='entretien_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doublons', to='entretien.entretien'),
        ),
    ]
