# Generated by Django 5.1.6 on 2025-05-21 00:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alarme', '0001_initial'),
        ('installations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('alarme', 'Alarme'), ('intervention', 'Intervention'), ('maintenance', 'Maintenance'), ('performance', 'Performance'), ('system', 'Système'), ('autre', 'Autre')], max_length=20, verbose_name='Type de notification')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Notification push'), ('in_app', "Dans l'application")], max_length=20, verbose_name='Canal')),
                ('envoyee_le', models.DateTimeField(auto_now_add=True, verbose_name='Envoyée le')),
                ('lue_le', models.DateTimeField(blank=True, null=True, verbose_name='Lue le')),
                ('priorite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Priorité')),
                ('alarme_associee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='alarme.alarmedeclenchee', verbose_name='Alarme associée')),
                ('installation_associee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='installations.installation', verbose_name='Installation associée')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-envoyee_le'],
            },
        ),
    ]
