# Generated by Django 5.1.6 on 2025-04-11 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarme', '0002_alarmecode_remove_alarme_equipement_and_more'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='alarme_associee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='alarme.alarmedeclenchee', verbose_name='Alarme associée'),
        ),
    ]
