# Generated by Django 5.1.6 on 2025-05-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'installation")),
                ('type_installation', models.CharField(choices=[('residential', 'Résidentiel'), ('commercial', 'Commercial'), ('industrial', 'Industriel'), ('utility', 'Utilitaire')], default='', max_length=20, verbose_name="Type d'installation")),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'En maintenance'), ('fault', 'En panne')], default='active', max_length=20, verbose_name='Statut')),
                ('date_installation', models.DateField(verbose_name="Date d'installation")),
                ('capacite_kw', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacité (kW)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('adresse', models.TextField(default='', verbose_name='Adresse')),
                ('ville', models.CharField(default='', max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(default='', max_length=20, verbose_name='Code postal')),
                ('pays', models.CharField(default='', max_length=100, verbose_name='Pays')),
                ('documentation_technique', models.FileField(blank=True, null=True, upload_to='documents_techniques/', verbose_name='Documentation technique')),
                ('expiration_garantie', models.DateField(blank=True, null=True, verbose_name='Fin de garantie')),
                ('reference_contrat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence contrat')),
                ('type_contrat', models.CharField(choices=[('exploitation', 'Exploitation'), ('preventive_curative', 'Préventive + Curative'), ('exploitation_curative', 'Exploitation + Curative')], default='exploitation', max_length=30, verbose_name='Type de contrat')),
                ('date_mise_en_service', models.DateField(blank=True, null=True, verbose_name='Date de mise en service')),
                ('statut_diagnostic', models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('traitee', 'Traitée')], default='en_attente', max_length=20, null=True, verbose_name='Statut diagnostic')),
                ('diagnostic_realise', models.BooleanField(default=False, verbose_name='Diagnostic réalisé')),
                ('devis_associe', models.FileField(blank=True, null=True, upload_to='devis/', verbose_name='Devis associé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('photo_installation', models.ImageField(blank=True, null=True, upload_to='installations/photos/', verbose_name="Photo de l'installation")),
            ],
            options={
                'verbose_name': 'Installation',
                'verbose_name_plural': 'Installations',
                'ordering': ['-date_installation'],
            },
        ),
    ]
