# Generated by Django 5.1.7 on 2025-04-02 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'installation")),
                ('type_installation', models.CharField(choices=[('residential', 'Résidentiel'), ('commercial', 'Commercial'), ('industrial', 'Industriel'), ('utility', 'Utilitaire')], default='', max_length=20, verbose_name="Type d'installation")),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'En maintenance'), ('fault', 'En panne')], default='active', max_length=20, verbose_name='Statut')),
                ('date_installation', models.DateField(verbose_name="Date d'installation")),
                ('capacite_kw', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacité (kW)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('adresse', models.TextField(default='', verbose_name='Adresse')),
                ('ville', models.CharField(default='', max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(default='', max_length=20, verbose_name='Code postal')),
                ('pays', models.CharField(default='', max_length=100, verbose_name='Pays')),
                ('documentation_technique', models.FileField(blank=True, null=True, upload_to='documents_techniques/', verbose_name='Documentation technique')),
                ('expiration_garantie', models.DateField(blank=True, null=True, verbose_name='Fin de garantie')),
                ('reference_contrat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence contrat')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('client', models.ForeignKey(default='', limit_choices_to={'groups__name': 'Clients'}, on_delete=django.db.models.deletion.CASCADE, related_name='installations', to=settings.AUTH_USER_MODEL)),
                ('installateur', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Installateurs'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systemes_installes', to=settings.AUTH_USER_MODEL)),
                ('technicien_assigne', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Techniciens'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_maintenues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Installation',
                'verbose_name_plural': 'Installations',
                'ordering': ['-date_installation'],
            },
        ),
    ]
