# Generated by Django 5.1.6 on 2025-05-21 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='client',
            field=models.ForeignKey(default='', limit_choices_to={'groups__name': 'Clients'}, on_delete=django.db.models.deletion.CASCADE, related_name='installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installation',
            name='installateur',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Installateurs'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systemes_installes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installation',
            name='techniciens',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Techniciens'}, related_name='installations_maintenues', to=settings.AUTH_USER_MODEL, verbose_name='Techniciens assignés'),
        ),
    ]
