# Generated by Django 5.1.7 on 2025-03-26 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='localisation',
        ),
        migrations.AddField(
            model_name='installation',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='alarme_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installation',
            name='capacite_kw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='installation',
            name='connecte_reseau',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='consommation_kw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='installation',
            name='dernier_controle',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='derniere_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='etat',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('En maintenance', 'En maintenance')], default='Actif', max_length=50),
        ),
        migrations.AddField(
            model_name='installation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='installation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='installation',
            name='production_actuelle_kw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='installation',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='installation',
            name='date_installation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='installation',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
