# Generated by Django 5.1.7 on 2025-04-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='photo_installation',
            field=models.ImageField(blank=True, null=True, upload_to='installations/', verbose_name="Photo de l'installation"),
        ),
    ]
