# Generated by Django 5.1.7 on 2025-04-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_installation_photo_installation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='photo_installation',
            field=models.ImageField(blank=True, null=True, upload_to='installations/photos/', verbose_name="Photo de l'installation"),
        ),
    ]
