# Generated by Django 5.1.7 on 2025-03-28 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_remove_installation_localisation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='proprietaire',
        ),
        migrations.AddField(
            model_name='installation',
            name='client',
            field=models.ForeignKey(blank=True, help_text="Le client propriétaire de l'installation", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installation',
            name='installateurs',
            field=models.ManyToManyField(blank=True, help_text="Les installateurs responsables de l'installation", related_name='installations_installateurs', to=settings.AUTH_USER_MODEL),
        ),
    ]
