# Generated by Django 5.1.6 on 2025-05-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0003_alter_installation_photo_installation'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='date_mise_en_service',
            field=models.DateField(blank=True, null=True, verbose_name='Date de mise en service'),
        ),
        migrations.AddField(
            model_name='installation',
            name='devis_associe',
            field=models.FileField(blank=True, null=True, upload_to='devis/', verbose_name='Devis associé'),
        ),
        migrations.AddField(
            model_name='installation',
            name='diagnostic_realise',
            field=models.BooleanField(default=False, verbose_name='Diagnostic réalisé'),
        ),
        migrations.AddField(
            model_name='installation',
            name='statut_diagnostic',
            field=models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('traitee', 'Traitée')], default='en_attente', max_length=20, null=True, verbose_name='Statut diagnostic'),
        ),
        migrations.AddField(
            model_name='installation',
            name='type_contrat',
            field=models.CharField(choices=[('exploitation', 'Exploitation'), ('preventive_curative', 'Préventive + Curative'), ('exploitation_curative', 'Exploitation + Curative')], default='exploitation', max_length=30, verbose_name='Type de contrat'),
        ),
    ]
