# Generated by Django 5.1.6 on 2025-05-15 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0004_installation_date_mise_en_service_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='technicien_assigne',
        ),
        migrations.AddField(
            model_name='installation',
            name='techniciens',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Techniciens'}, related_name='installations_maintenues', to=settings.AUTH_USER_MODEL, verbose_name='Techniciens assignés'),
        ),
    ]
