# Generated by Django 5.1.7 on 2025-04-02 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('panel', 'Panneau solaire'), ('inverter', 'Onduleur'), ('battery', 'Batterie'), ('meter', 'Compteur'), ('monitoring', 'Système de monitoring'), ('other', 'Autre')], max_length=20, verbose_name="Type d'équipement")),
                ('model_number', models.CharField(max_length=100, verbose_name='Numéro de modèle')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de série')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Fabricant')),
                ('installation_date', models.DateField(verbose_name="Date d'installation")),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Fin de garantie')),
                ('technical_specs', models.JSONField(blank=True, null=True, verbose_name='Spécifications techniques')),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code QR')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='installations.installation', verbose_name='Installation associée')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['equipment_type', 'model_number'],
                'indexes': [models.Index(fields=['serial_number'], name='equipements_serial__ae874a_idx'), models.Index(fields=['equipment_type'], name='equipements_equipme_c251a9_idx')],
            },
        ),
    ]
