# Generated by Django 5.1.6 on 2025-05-13 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installations', '0004_installation_date_mise_en_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_appareil', models.CharField(choices=[('onduleur', 'Onduleur'), ('compteur', 'Compteur'), ('micro-onduleur', 'Micro-onduleur'), ('batterie', 'Batterie'), ('station_meteo', 'Station météo'), ('boite_jonction', 'Boîte de jonction'), ('repetiteur', 'Répéteur'), ('ventilateur', 'Ventilateur'), ('erm', 'ERM')], max_length=50)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('etat', models.CharField(default='actif', max_length=50)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='installations.installation')),
            ],
        ),
    ]
