# Generated by Django 5.1.6 on 2025-05-14 15:55

import equipements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='code_unique',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to=equipements.models.qr_code_upload_path),
        ),
    ]
