# Generated by Django 5.1.7 on 2025-03-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='modele',
        ),
        migrations.AlterField(
            model_name='equipement',
            name='marque',
            field=models.CharField(choices=[('Huawei', 'Huawei'), ('Schneider', 'Schneider'), ('Tesla', 'Tesla')], max_length=50),
        ),
    ]
