# Generated by Django 5.1.6 on 2025-05-21 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0001_initial'),
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='installations.installation'),
        ),
    ]
