# Generated by Django 5.1.6 on 2025-05-14 15:55

from django.db import migrations
import uuid


def generate_unique_code(apps, schema_editor):
    Equipement = apps.get_model('equipements', 'Equipement')
    for equipement in Equipement.objects.all():
        equipement.code_unique = str(uuid.uuid4())
        equipement.save()

class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0002_equipement_code_unique_equipement_qr_code_image'),
    ]

    operations = [
      migrations.RunPython(generate_unique_code),

    ]
