# Generated by Django 5.1.6 on 2025-05-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0003_populate_code_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='code_unique',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
