# Generated by Django 5.1.7 on 2025-03-26 03:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_alarme', models.CharField(max_length=100)),
                ('niveau_criticite', models.CharField(choices=[('Faible', 'Faible'), ('Moyenne', 'Moyenne'), ('Critique', 'Critique'), ('Urgent', 'Urgent')], default='Moyenne', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Active', 'Active'), ('Résolue', 'Résolue'), ('Ignorée', 'Ignorée'), ('En attente', 'En attente')], default='Active', max_length=50)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarmes', to='equipements.equipement')),
            ],
        ),
    ]
