# Generated by Django 5.1.7 on 2025-04-02 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0001_initial'),
        ('installations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_alarme', models.CharField(max_length=50, verbose_name="Code d'alarme")),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('gravite', models.CharField(choices=[('critical', 'Critique'), ('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Basse')], max_length=20, verbose_name='Gravité')),
                ('statut', models.CharField(choices=[('open', 'Ouverte'), ('acknowledged', 'Reconnue'), ('in_progress', 'En cours'), ('resolved', 'Résolue'), ('false', 'Fausse alarme')], default='open', max_length=20, verbose_name='Statut')),
                ('declenchee_le', models.DateTimeField(auto_now_add=True, verbose_name='Déclenchée le')),
                ('reconnue_le', models.DateTimeField(blank=True, null=True, verbose_name='Reconnue le')),
                ('resolue_le', models.DateTimeField(blank=True, null=True, verbose_name='Résolue le')),
                ('automatique', models.BooleanField(default=True, verbose_name='Générée automatiquement')),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarmes', to='equipements.equipment', verbose_name='Équipement')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarmes', to='installations.installation', verbose_name='Installation')),
                ('reconnue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarmes_reconnues', to=settings.AUTH_USER_MODEL, verbose_name='Reconnue par')),
                ('resolue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarmes_resolues', to=settings.AUTH_USER_MODEL, verbose_name='Résolue par')),
            ],
            options={
                'verbose_name': 'Alarme',
                'verbose_name_plural': 'Alarmes',
                'ordering': ['-declenchee_le'],
            },
        ),
    ]
