# Generated by Django 5.1.6 on 2025-04-11 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarme', '0001_initial'),
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(choices=[('Huawei', 'Huawei'), ('Kstar', 'Kstar'), ('Solax', 'Solax')], max_length=50)),
                ('type_alarme', models.CharField(choices=[('DC', 'Partie DC'), ('Terre', 'Partie Terre'), ('AC', 'Partie AC'), ('Logiciel', 'Logiciel'), ('autre', 'Autre')], max_length=50)),
                ('code_constructeur', models.CharField(max_length=50)),
                ('gravite', models.CharField(choices=[('critique', 'Critique'), ('majeure', 'Majeure'), ('mineure', 'Mineure')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='alarme',
            name='equipement',
        ),
        migrations.RemoveField(
            model_name='alarme',
            name='installation',
        ),
        migrations.RemoveField(
            model_name='alarme',
            name='reconnue_par',
        ),
        migrations.RemoveField(
            model_name='alarme',
            name='resolue_par',
        ),
        migrations.CreateModel(
            name='AlarmeDeclenchee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_declenchement', models.DateTimeField(auto_now_add=True)),
                ('est_resolue', models.BooleanField(default=False)),
                ('code_alarme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='alarme.alarmecode')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarmes_declenchees', to='installations.installation')),
            ],
        ),
    ]
