# Generated by Django 5.1.7 on 2025-04-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmecode',
            name='est_resolue',
            field=models.BooleanField(default=False),
        ),
    ]
