# Generated by Django 5.1.6 on 2025-04-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarme', '0002_alarmecode_remove_alarme_equipement_and_more'),
        ('notification', '0002_alter_notification_alarme_associee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alarme',
        ),
    ]
