# Generated by Django 5.1.7 on 2025-04-02 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionConsommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(null=True, verbose_name='Horodatage')),
                ('energie_produite_kwh', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Énergie produite (kWh)')),
                ('energie_consomme_kwh', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Énergie consommée (kWh)')),
                ('puissance_maximale_kw', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Puissance maximale (kW)')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Température (°C)')),
                ('irradiation_wh_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Irradiation (Wh/m²)')),
                ('ratio_performance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ratio de performance')),
                ('est_prediction', models.BooleanField(default=False, verbose_name='Donnée prédite')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees_production', to='installations.installation', verbose_name='Installation')),
            ],
            options={
                'verbose_name': 'Donnée de production/consommation',
                'verbose_name_plural': 'Données de production/consommation',
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['installation', 'horodatage'], name='production__install_851d56_idx')],
            },
        ),
    ]
