# Generated by Django 5.1.7 on 2025-03-26 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installations', '0002_remove_installation_localisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionConsommation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('production_kw', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rendement_panneaux', models.DecimalField(decimal_places=2, default=0.0, help_text='Efficacité des panneaux en %', max_digits=5)),
                ('temperature_panneaux', models.DecimalField(blank=True, decimal_places=2, help_text='Température des panneaux (°C)', max_digits=5, null=True)),
                ('consommation_kw', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pic_consommation', models.TimeField(blank=True, help_text='Heure du pic de consommation', null=True)),
                ('autoconsommation_pourcentage', models.DecimalField(decimal_places=2, default=0.0, help_text="Part de l'énergie autoconsommée (%)", max_digits=5)),
                ('energie_stockee_kw', models.DecimalField(blank=True, decimal_places=2, help_text='Énergie stockée (kW)', max_digits=10, null=True)),
                ('energie_reinjectee_kw', models.DecimalField(blank=True, decimal_places=2, help_text='Énergie envoyée vers le réseau (kW)', max_digits=10, null=True)),
                ('etat_batterie', models.DecimalField(blank=True, decimal_places=2, help_text='Charge batterie (%)', max_digits=5, null=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees_energie', to='installations.installation')),
            ],
        ),
    ]
