# Generated by Django 5.1.7 on 2025-04-12 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name="Description de l'intervention")),
                ('date_prevue', models.DateTimeField(verbose_name="Date d'intervention prévue")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('client', models.ForeignKey(limit_choices_to={'groups__name': 'Clients'}, on_delete=django.db.models.deletion.CASCADE, related_name='interventions_demandees', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='installations.installation', verbose_name='Installation concernée')),
                ('technicien', models.ForeignKey(limit_choices_to={'groups__name': 'Techniciens'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Technicien assigné')),
            ],
            options={
                'verbose_name': "Fiche d'intervention",
                'verbose_name_plural': "Fiches d'intervention",
                'ordering': ['-date_prevue'],
            },
        ),
    ]
