# Generated by Django 5.1.6 on 2025-05-21 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(choices=[('diagnostic', 'Diagnostic'), ('preventive', 'Préventive'), ('curative', 'Curative')], default='diagnostic', max_length=20, verbose_name="Type d'intervention")),
                ('description', models.TextField(verbose_name="Description de l'intervention")),
                ('date_prevue', models.DateTimeField(verbose_name="Date d'intervention prévue")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='installations.installation', verbose_name='Installation concernée')),
            ],
            options={
                'verbose_name': "Fiche d'intervention",
                'verbose_name_plural': "Fiches d'intervention",
                'ordering': ['-date_prevue'],
            },
        ),
    ]
