# Generated by Django 5.1.6 on 2025-05-21 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intervention', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheintervention',
            name='technicien',
            field=models.ForeignKey(limit_choices_to={'role': 'technicien'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Technicien assigné'),
        ),
    ]
