# Generated by Django 5.1.7 on 2025-04-12 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0002_alter_ficheintervention_technicien'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheintervention',
            name='client',
        ),
        migrations.AlterField(
            model_name='ficheintervention',
            name='technicien',
            field=models.ForeignKey(limit_choices_to={'role': 'technicien'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Technicien assigné'),
        ),
    ]
