# Generated by Django 5.1.7 on 2025-05-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0003_remove_ficheintervention_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheintervention',
            name='type_intervention',
            field=models.CharField(choices=[('diagnostic', 'Diagnostic'), ('preventive', 'Préventive'), ('curative', 'Curative')], default='diagnostic', max_length=20, verbose_name="Type d'intervention"),
        ),
    ]
